Update handling of Project EvaluatorSettings for Pkl 0.26.0
apple/pkl-go pull request #79
Opened 2024-06-24 00:43 UTC by HT154

Currently, using pkl-go to evaluate using a PklProject always yields a warning:
```
warn: Cannot find field on Go struct `pkl.ProjectEvaluatorSettings` matching Pkl property `http`. Ensure the Go structs are up to date with Pkl classes either through codegen or manually adding `pkl` tags.
```

The `http` field is populated to avoid the above warning. I opted to reuse the existing `Http` and `Proxy` structs here, but I'm unsure if this is the preferred approach over defining new structs. Happy to change direction on this based on feedback.

This PR also changes `ProjectEvaluatorSettings` to `EvaluatorSettings` to reflect that this struct now maps to its own stdlib module. This is a breaking change, but it matches the one in the stdlib and it's less likely clients are using this API directly. One concern I have here is that the name `EvaluatorSettings` could potentially cause confusion with `EvaluatorOptions`. I see value in mirroring the stdlib here, but can revert this if folks feel strongly.

2024-06-24 17:37 UTC, bioball requested changes

2024-06-24 17:37 UTC, bioball commented on pkl/project.go
> +type EvaluatorSettings struct {
I don't feel great about the name clash between `EvaluatorOptions` and `EvaluatorSettings`.

Some other ideas:

* Move all of these to a sub-package; e.g. `stdlib` or something that.
* Name it `PklEvaluatorSettings`

I think let's keep this name for now, and we can handle this in another PR?

2024-06-24 17:37 UTC, bioball commented on pkl/project_test.go
> +			expectedSettings := &pkl.EvaluatorSettings{
Two issues here (per failing tests):

1. The evaluator settings should have `Http`
2. Rewrite test to pass on Pkl 0.25 (probably need different tests for the different versions)

2024-06-24 17:37 UTC, bioball commented on pkl/project.go
> +	Http               *Http             `pkl:"http"`
Let's use a different struct, because these are slightly different (CA certificate options doesn't exist here).

2024-06-24 18:49 UTC, HT154 commented on pkl/project_test.go
> +	if pklVersion0_26.isGreaterThan(version) {
I had to hoist this file into the `pkl` package to access this private member, hence most of the diff in the existing test.

2024-07-03 19:42 UTC, bioball approved these changes
LGTM, thank you!

2024-07-03 19:43 UTC, merged